### ISSUE TITLE
Would be nice to omit the history of a job upon reschedule

### ISSUE THREAD

**Issue by DirkStevens** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#43]
Hey Max, I plan rescheduling some jobs indefinitely, so it would nice to omit the history of a job because I am afraid the history of the job will just grow for no reason.

**Comment by msavin** [comment]
You should look into the `replicate` and `remove` feature. 

More info:
https://github.com/msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks/blob/master/CHANGES.md
