### ISSUE TITLE
Rescheduling a job without time parameters or time difference less then jobs timer interval does not work

### ISSUE THREAD

**Issue by DirkStevens** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#44]
Rescheduling a job without time parameters or time difference less then jobs timer interval is never executed?

Should always reschedule with time parameters larger than jobs timer interval ?

**Comment by msavin** [comment]
@DirkStevens fixed, please update to 3.0.4 and try again.

**Comment by DirkStevens** [comment]
Thanks @msavin
