### ISSUE TITLE
Jobs.configure fails when setting the timer

### ISSUE THREAD

**Issue by DirkStevens** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#45]
Jobs.configure({
		timer: 1000
	});

Error: Match error: Unknown key in field timer
W20180317-17:34:57.953(1)? (STDERR)     at check (packages/check/match.js:35:15)
W20180317-17:34:57.954(1)? (STDERR)     at Object.Jobs.configure (packages/msavin:sjobs/server/api.js:10:2)

**Comment by DirkStevens** [comment]
Looks like the documentation is off, in the v3 "timer" apparently changed to "interval"...

This works:

	Jobs.configure({
		interval: 1000
	});

**Comment by msavin** [comment]
@DirkStevens Where did you find `timer`? I believe I changed it everywhere that it showed up 🤔
