### ISSUE TITLE
can i Jobs.run("Job_B") in Jobs.register({"Job_A":function(){}}) ?

### ISSUE THREAD

**Issue by fangjj** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#46]
I have many cron job. but i don't know each cron job how much time will take and some cron job have related order. for example, Job_A finished Job_B begin, so Job_B begin time is difficult to be set.

**Comment by msavin** [comment]
why not? :)

**Comment by fangjj** [comment]
yeah, it did work. thank you.
