### ISSUE TITLE
msavin:sjobs-ui-blaze display no data.

### ISSUE THREAD

**Issue by fangjj** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#47]
I add msavin:sjobs-ui-blaze and msavin:sjobs, then i press Control + J in your app to open it, but display no data.

**Comment by msavin** [comment]
Coming soon - it will be ready once 3.0 gets announced

**Comment by msavin** [comment]
@fangjj @mozfet okay its live :) let me know how it works

**Comment by fangjj** [comment]
nice job!
