### ISSUE TITLE
how to add many workers to do the job?

### ISSUE THREAD

**Issue by fangjj** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#48]
I want to two and many meteor servers worker to do the same job. just like rabbitmq work_queues.http://www.rabbitmq.com/tutorials/tutorial-two-javascript.html

1. Started two Meteor servers, which connect to the same database.
2. Registered the same job on two Meteor servers.
3. Then i Schedule many jobs.
4. I want two server execute different job, just like
![image](https://user-images.githubusercontent.com/15318800/38020386-a820eb6e-32ac-11e8-9096-3f64dc175e92.png)
5. But now each job was executed by two server.
![image](https://user-images.githubusercontent.com/15318800/38020702-8afa5632-32ad-11e8-95db-a9e9abfe46fb.png)

**Comment by gary-menzel** [comment]
At present, the package doesn't work that way.  You can have multiple servers but only one of them runs the workers.  If that one stops responding then one of the others picks up the jobs and becomes the dominating server.

**Comment by fangjj** [comment]
yes, the package just keep one server run one job at a time

**Comment by msavin** [comment]
👍
