### ISSUE TITLE
Manipulating data of jobs_data and jobs_dominator collections from the app.

### ISSUE THREAD

**Issue by gjakab** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#49]
Hi, is it possible somehow to for example delete data from these collections inside the meteor app (without using the mongodb console)? I'm thinking something like Jobs.remove() to clear the whole jobs database.

**Comment by gary-menzel** [comment]
You can import the `JobsInternal` module that contains the `Utilities` module that exposes the `collection` (which is just a normal collection) and do whatever you like against that.

**Comment by msavin** [comment]
Gary said it.

Maybe its time to expose the collection as `Jobs.collection`

**Comment by msavin** [comment]
You could also run Jobs.clear("*") to remove everything

**Comment by msavin** [comment]
Code pushed - coming in next version
