### ISSUE TITLE
Cannot read property 'insert' of undefined

### ISSUE THREAD

**Issue by rapidmon17** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#52]
For my first run, I copied and pasted the example in the docs.
I created a file called worker.js with the following contents:

```
import { Jobs } from 'meteor/msavin:sjobs';



Jobs.register({
    "sendReminder": function (to, message) {
        var call = HTTP.put("http://www.magic.com/sendEmail", {
            to: to,
            message: message
        })

        if (call.statusCode === 200) {
            this.success(call.result);
        } else {
            this.reschedule({
                in: {
                    minutes: 5
                }
            });
        }
    }
});


Jobs.run("sendReminder", "jony@apple.com", "The future is here!", {
    in: {
        days: 3,
    }, 
    on: {
        hour: 9,
        minute: 42
    },
    priority: 9999999999
});
```

As a result my Meteor app is crashing with the following stacktrace:

> W20180611-01:37:40.752(-4)? (STDERR) TypeError: Cannot read property 'insert' of undefined
> W20180611-01:37:40.752(-4)? (STDERR)     at add (packages/msavin:sjobs/server/imports/actions/add/index.js:31:35)
> W20180611-01:37:40.752(-4)? (STDERR)     at Object.Jobs.run (packages/msavin:sjobs/server/api.js:55:22)
> W20180611-01:37:40.752(-4)? (STDERR)     at workers.js (imports/api/workers.js:25:6)
> W20180611-01:37:40.752(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
> W20180611-01:37:40.762(-4)? (STDERR)     at require (packages/modules-runtime.js:238:16)
> W20180611-01:37:40.763(-4)? (STDERR)     at main.js (server/main.js:1:524)
> W20180611-01:37:40.763(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
> W20180611-01:37:40.763(-4)? (STDERR)     at require (packages/modules-runtime.js:238:16)
> W20180611-01:37:40.764(-4)? (STDERR)     at /Users/rapidmon17/Projects/hello/.meteor/local/build/programs/server/app/app.js:1266:1
> W20180611-01:37:40.764(-4)? (STDERR)     at /Users/rapidmon17/Projects/hello/.meteor/local/build/programs/server/boot.js:411:36
> W20180611-01:37:40.764(-4)? (STDERR)     at Array.forEach (<anonymous>)
> W20180611-01:37:40.764(-4)? (STDERR)     at /Users/rapidmon17/Projects/hello/.meteor/local/build/programs/server/boot.js:220:19
> W20180611-01:37:40.764(-4)? (STDERR)     at /Users/rapidmon17/Projects/hello/.meteor/local/build/programs/server/boot.js:471:5
> W20180611-01:37:40.764(-4)? (STDERR)     at Function.run (/Users/rapidmon17/Projects/hello/.meteor/local/build/programs/server/profile.js:510:12)
> W20180611-01:37:40.764(-4)? (STDERR)     at /Users/rapidmon17/Projects/hello/.meteor/local/build/programs/server/boot.js:470:11

**Comment by rapidmon17** [comment]
I must be doing something wrong since no one else is running into this problem. Can someone help me? Thanks.

**Comment by msavin** [comment]
@rapidmon17 

hmm, can you try to run the code after Meteor.startup? I suspect that the Jobs.run() function is being called too soon, before Meteor has had the chance to initialize the MongoDB collection

**Comment by rapidmon17** [comment]
I believe you're right.
