### ISSUE TITLE
Correct way to run recurring job

### ISSUE THREAD

**Issue by mozfet** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#54]
I want to implement a monthly billing function using a job. The billing should occur every 30 days after the user subscribed to a service until canceled.

From the documentation, I understand I cannot mark a job as successful and then reschedule it (reschedule is only for failed jobs). Should I replicate the job after setting this.success in the register job function, or what is the best practice for a repeating job?

**Comment by msavin** [comment]
@mozfet you would want to use `this.replicate` to schedule the next job, and then `this.success` to resolve the current one.

**Comment by mozfet** [comment]
ok thx
