### ISSUE TITLE
call this.set(key, value) get error!

### ISSUE THREAD

**Issue by fangjj** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#55]
TypeError: Cannot set property 'count' of undefined
at toolbelt.set (packages/msavin:sjobs/server/imports/actions/execute/toolbelt.js:27:4)
```
// first, update the document
		var update = Utilities.collection.update(docId, {
			$set: patch
		})
	
		// second, patch the cached document if write is successful
		if (update) {
			this.document.data[key] = value
		}
```
because this.document.data is undefined!

same reason, self.get(key), if key is not exist, get error!
TypeError: Cannot read property 'count1' of undefined
 at toolbelt.get (packages/msavin:sjobs/server/imports/actions/execute/toolbelt.js:48:10)
```
return this.document.data[key] || null;
```
because this.document.data is undefined!

**Comment by msavin** [comment]
I think it's `docId` that is causing the issue.. should be `jobDoc._id`. Thanks for pointing it out, I'll get a fix out soon.

**Comment by msavin** [comment]
@fangjj are you sure you are using the latest version? I just checked, and it was working fine locally.

Can you post your job code as well?

**Comment by fangjj** [comment]
@msavin , msavin:sjobs@3.0.6
msavin:sjobs-ui-blaze@3.0.1
METEOR@1.7.0.3

**Comment by msavin** [comment]
@fangjj I think this is resolved in the new version. If you continue to run into issues please let me know.
