### ISSUE TITLE
Inconsistent timing

### ISSUE THREAD

**Issue by chris-gong** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#59]
Hello, I've been using meteor promises with the jobs package and it seems that when I try to run or reschedule, the job usually runs at a rate faster than expected. When the job runs faster than expected, the code hasn't changed from before. Whenever I restart the meteor app the job may or may not run at the expected rate. A decent amount of this code was from this issue https://github.com/msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks/issues/31, so I'm not sure if this error only occurs in the case of asynchronous functions.
```
import {Jobs} from 'meteor/msavin:sjobs';
import {sendEmail} from './emailUtils.js';
import { Promise } from 'meteor/promise';

function registerEmailJob({name, run}){
  Jobs.register({
    [name](...parameters){
      Promise.await(run.apply(this, parameters));
    }
  });
}

registerEmailJob({
  name: 'sendReminder',
  async run() {
    try{
      const result = await sendEmail();
      this.reschedule({
        in: {
          minutes: 1
        }
      });
    }
    catch(error){
      console.log(error);
      this.failure(error);
    }
  }
});

Meteor.startup(() => {
  Jobs.run("sendReminder", {
    in: {
      minutes: 1
    }
  });
});
```
I've tried using `seconds:60` and `milliseconds: 60000` in the configuration object and the jobs still run very fast (2-8 emails are sent every minute). `sendEmail` is a function that uses the nodemailer package to send an email, and it returns a promise.

**Comment by msavin** [comment]
@chris-gong most likely, the job is running more than once because you are adding it to the queue every time the server starts up. This revision should help prevent that:

```
Meteor.startup(() => {
  Jobs.run("sendReminder", {
    singular: true,
    in: {
      minutes: 1
    }
  });
});
```

**Comment by chris-gong** [comment]
hey @msavin sorry for the late reply but your suggestion works, really appreciate it. Just wondering, is there a preferred place for running Jobs.run(...) if not in meteor.startup? Thanks again
