### ISSUE TITLE
sjobs-ui-blaze interferes with login process

### ISSUE THREAD

**Issue by tosinek** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#61]
When I add the UI package (for which I can't find readable source code), my login process breaks and I can't use LDAP authentication anymore (babrahams:accounts-ldap). I can stay logged in if I were logged in before, but no new logins work.

from console:
```
LDAP authentication for: tom
Trying to bind tom@domain.com...
Callback from binding LDAP:
```
The next two lines should be (but they never appear)
```
Searching DC=domain,DC=com
User successfully retrieved from LDAP server
```

Where can I find readable source code for the UI package?
Thank you

**Comment by msavin** [comment]
Are you sure? It does nothing related to accounts/etc
