### ISSUE TITLE
[SOLVED] Where do we get the docID when we schedule a job?

### ISSUE THREAD

**Issue by ZhaopingLuo** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#67]
I tried `console.log(this.doc());` in my Jobs.register to see what we have, but it's not a function.

this.doc() - access job document

Since we use this ID everywhere, there should be some way to retrieve my new job ID, right?

**Comment by msavin** [comment]
Documentation error. Please try this.document._id
